#include <glad/glad.h>
#include "ShaderTypes.h"

const unsigned TEXTURE_BASIC_COLOR_UNIT  = GL_TEXTURE1;
const int      TEXTURE_BASIC_COLOR_INDEX = 1;

const unsigned TEXTURE_NORMAL_UNIT  = GL_TEXTURE2;
const int      TEXTURE_NORMAL_INDEX = 2;

const unsigned TEXTURE_EMISSIVE_UNIT  = GL_TEXTURE3;
const int      TEXTURE_EMISSIVE_INDEX = 3;

const unsigned TEXTURE_METALLIC_ROUGHNESS_UNIT  = GL_TEXTURE4;
const int      TEXTURE_METALLIC_ROUGHNESS_INDEX = 4;

const unsigned TEXTURE_OCCLUSION_UNIT  = GL_TEXTURE5;
const int      TEXTURE_OCCLUSION_INDEX = 5;

const unsigned TEXTURE_DEPTH_MAP_UNIT  = GL_TEXTURE10;
const int      TEXTURE_DEPTH_MAP_INDEX = 10;

const unsigned TEXTURE_SHADOW_MAP_UNIT  = GL_TEXTURE11;
const int      TEXTURE_SHADOW_MAP_INDEX = 11;

const unsigned TEXTURE_SKYBOX_UNIT  = GL_TEXTURE12;
const int      TEXTURE_SKYBOX_INDEX = 12;

const unsigned TEXTURE_IRRADIANCE_MAP_UNIT  = GL_TEXTURE13;
const int      TEXTURE_IRRADIANCE_MAP_INDEX = 13;

const unsigned TEXTURE_PREFILTER_MAP_UNIT  = GL_TEXTURE14;
const int      TEXTURE_PREFILTER_MAP_INDEX = 14;

const unsigned TEXTURE_BRDF_LUT_UNIT  = GL_TEXTURE15;
const int      TEXTURE_BRDF_LUT_INDEX = 15;

const unsigned TEXTURE_BLOOM_UNIT  = GL_TEXTURE16;
const int      TEXTURE_BLOOM_INDEX = 16;

const unsigned TEXTURE_VELOCITY_UNIT  = GL_TEXTURE17;
const int      TEXTURE_VELOCITY_INDEX = 17;

const unsigned TEXTURE_TAA_HISTORY_UNIT  = GL_TEXTURE18;
const int      TEXTURE_TAA_HISTORY_INDEX = 18;
